### PR TITLE
fix: fix topology insights not loading

### LINKED ISSUE #1242: Topology Insights is Broken
The `InsightsDetails` details component currently only supports configs, instead of both topology and configs, meaning it's broken for the UI.

image

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1242

### CODE REVIEW

File: src/api/services/configs.ts [hunk 1]
```diff
@@ -335,7 +335,7 @@ export const getConfigInsights = async <T>(
     }`;
   }
   return resolve(
-    ConfigDB.get<T>(
+    ConfigDB.get<ConfigTypeInsights[]>(
       `/config_analysis?select=*,config:configs(id,name,config_class,type)&config_id=eq.${configId}${paginationQueryParams}`,
```
Comment (moshloop) [inline src/api/services/configs.ts:339]: We shouldn't be getting all columnes

File: src/api/services/configs.ts [hunk 2]
```diff
@@ -335,8 +335,8 @@ export const getConfigInsights = async <T>(
     }`;
   }
   return resolve(
-    ConfigDB.get<T>(
-      `/config_analysis?select=*,config:configs(id,name,config_class,type)&config_id=eq.${configId}${paginationQueryParams}`,
+    ConfigDB.get<ConfigTypeInsights[]>(
+      `/config_analysis?select=id,source,analyzer,analysis_type,message,severity,status,analysis,first_observed,config:configs(id,name,config_class,type)&config_id=eq.${configId}${paginationQueryParams}`,
```
Comment (moshloop) [inline src/api/services/configs.ts:339]: We shouldn't be including analysis as its pretty large - It should only show on the popup window
