### PR TITLE
fix: improve the playbook dropdown menu

### LINKED ISSUE #2193: Playbook menu improvements
- Add a tag for category
- Use playbook icon (And for the main sidebar)
- Reduce text size and padding and increase width

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #2193

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe - The button size is fine, its the menu elements that need to be smaller font, and padding + alight the dropdown to the left, not to the right

File: src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx [hunk 1]
```diff
@@ -46,40 +51,38 @@ export default function PlaybooksDropdownMenu({
...
-              <ChevronDownIcon
-                className="-mr-1 ml-2 h-5 w-5"
-                aria-hidden="true"
-              />
-            </Menu.Button>
+          <MenuButton className="btn-white px-2 py-1">
+            <Icon name="playbook" className="mr-2 mt-0.5 h-4 w-4" />
+            Playbooks
+            <ChevronDownIcon
+              className="-mr-1 ml-2 h-5 w-5"
```
Comment (moshloop) [inline src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx:58]:
```suggestion
              className="-mr-1 ml-2 h-5 w-5 text-gray-400"
```

File: src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx [hunk 2]
```diff
@@ -46,40 +51,38 @@ export default function PlaybooksDropdownMenu({
...
+            enterTo="transform opacity-100 scale-100"
+            leave="transition ease-in duration-75"
+            leaveFrom="transform opacity-100 scale-100"
+            leaveTo="transform opacity-0 scale-95"
+          >
+            <MenuItems portal className="menu-items" anchor="bottom start">
+              {playbooks?.map((playbook) => (
+                <MenuItem
+                  as="button"
+                  className="menu-item w-auto max-w-fit text-xs"
```
Comment (moshloop) [inline src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx:77]:
```suggestion
                  className="menu-item w-full"
```

File: src/components/Playbooks/Runs/Actions/PlaybookResultsDropdownButton.tsx [hunk 3]
```diff
@@ -74,37 +79,31 @@ export default function PlaybookResultsDropdownButton({
 
   return (
     <Menu as="div">
-      <Float placement="bottom-end" portal>
-        <Menu.Button className="absolute right-5 top-5 z-[99999] text-lg">
-          <FaCog className="h-4 w-4" />
-        </Menu.Button>
+      <MenuButton className="absolute right-5 top-5 z-[99999] text-lg">
+        <FaCog className="h-4 w-4" />
```
Comment (moshloop) [inline src/components/Playbooks/Runs/Actions/PlaybookResultsDropdownButton.tsx:83]:
```suggestion
        <FaCog className="h-5 w-5" />
```

File: src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx [hunk 4]
```diff
@@ -46,40 +51,38 @@ export default function PlaybooksDropdownMenu({
...
-            <Menu.Button className="btn-white">
-              <FaCog className="mr-2 mt-0.5 h-4 w-4" />
-              Playbooks
-              <ChevronDownIcon
-                className="-mr-1 ml-2 h-5 w-5"
-                aria-hidden="true"
-              />
-            </Menu.Button>
+          <MenuButton className="btn-white px-2 py-1">
+            <Icon name="playbook" className="mr-2 mt-0.5 h-4 w-4" />
```
Comment (moshloop) [inline src/components/Playbooks/Runs/Submit/PlaybooksDropdownMenu.tsx:55]:
```suggestion
            <Icon name="playbook" className="mr-2 mt-0.5 h-5 w-5" />
```

File: package.json [hunk 5]
```diff
@@ -11,10 +11,9 @@
     "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
     "@clerk/nextjs": "^5.3.0",
     "@dagrejs/dagre": "^1.1.1",
-    "@flanksource/icons": "^1.0.25",
+    "@flanksource/icons": "^1.0.28",
```
Comment (moshloop) [inline package.json:14]:
```suggestion
    "@flanksource/icons": "^1.0.29",
```
