### PR TITLE
FLNK-1072 - Incident Action Plan - Create factor/solution improvements

### LINKED ISSUE #1072: Incident Action Plan - Create factor/solution improvements
- The modal footer is not style the same as other dialogs 
- The dropdown should be full width
- The title input field font is wrong
- The action plan title is duplicated (it is already in the tab title)

### PR DESCRIPTION
**Pull request by gitstart-flanksource**
Closes #1072

### Before Solving 
[Incidents _ Mission Control.webm](https://github.com/GitStartHQ/client-flanksource/assets/58044533/d28dd310-5254-4fe1-94fb-ca443f6e03a6)

### After Solving
https://www.awesomescreenshot.com/video/17681836

https://www.loom.com/share/b880810550fa4e72b2a15978b9da1230?sid=803e26f1-de3f-4c80-8cc0-56b3f4f7c033

image

image

image

### CODE REVIEW

**Comment by gitstart-flanksource** [comment]
@moshloop this PR is ready for review

File: src/components/Incidents/IncidentCreate/index.tsx [hunk 1]
```diff
@@ -255,34 +258,35 @@ export function IncidentCreate({
...
+              items={incidentStatusItems}
+              labelClass="block text-sm font-bold text-gray-700 mb-2"
+              containerClassName="flex flex-col space-y-1"
+              value={status}
+            />
+            <p className="text-red-600 text-sm">{errors.status?.message}</p>
+          </div>
         </div>
-        <div className="flex justify-end">
+        <div className="flex justify-end bg-gray-100 px-5 py-4 w-full rounded">
```
Comment (moshloop) [inline src/components/Incidents/IncidentCreate/index.tsx:289]: This button should be the same style as the others and should use the <Button> component rather than the button dom element

**Comment by gitstart-flanksource** [comment]
Thanks for the feedback @moshloop, we are on it

**Comment by gitstart-flanksource** [comment]
Your feedback has been implemented @moshloop
