### PR TITLE
fix: add tooltip to show full tag name for tags

### LINKED ISSUE #2124: Use tooltip to show full tag name for tags
Currently we display tags as only values, if we hover over it, we should get `key:value`

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #2124

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe Can we move the include / exclude icons into the tooltip ?

File: src/ui/Tags/Tag.tsx [hunk 1]
```diff
@@ -26,35 +27,50 @@ export function Tag({
...
   return (
-    <div
-      className={clsx(
-        className,
-        variant === "gray" && "bg-gray-100 text-gray-600",
-        variant === "blue" && "bg-blue-100 text-blue-800",
-        onFilterByTag && "group"
+    <>
+      <div
+        data-tooltip-id={`${id}-${tag?.key}-${tag?.value}`}
```
Comment (moshloop) [inline src/ui/Tags/Tag.tsx:37]:
```suggestion
        data-tooltip-id={`${id}-${tag?.key}-${tag?.value}`}
        data-tooltip-delay-show={100}
```

**Comment by moshloop** [comment]
@mainawycliffe can we put the icons on their own row, middle aligned so that the mouse cursor goes up, with no chance of the tooltip disappearing before reaching the icon
