### PR TITLE
fix: config evidence item icon issue

### LINKED ISSUE #759: Config Evidence Items icons are not show
In the comment view and definition of done list

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #759

### CODE REVIEW

File: src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx [hunk 1]
```diff
@@ -151,11 +151,7 @@ function ConfigEvidence({
 
   return (
     <div className={clsx("overflow-hidden p-2", className)} {...rest}>
-      <Icon
-        name={config.external_type}
-        secondary={config.config_type}
-        size="lg"
-      />{" "}
+      <Icon name={config.external_type || config.config_type} />{" "}
```
Comment (moshloop) [inline src/components/IncidentDetails/DefinitionOfDone/EvidenceView/index.tsx:154]: Both of these needs to passed through, external_type might not be null, but also not have a corresponding icon
