### PR TITLE
fix: update dropdowns & sidebar panels content font styles

### LINKED ISSUE #1200: Change default font-size to  text-sm
- All dropdown bodes
- Sidebar panel bodies

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #1200

### CODE REVIEW

File: src/components/IncidentsFilterBar/index.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export default function TopologyOpenIncidentsFilterBar({
         name="type"
         control={control}
         prefix={"Type:"}
-        className="border-none shadow-none font-semibold space-x-3 capitalize text-base px-2"
+        className="border-none shadow-none font-semibold space-x-3 capitalize text-sm px-2"
```
Comment (moshloop) [inline src/components/IncidentsFilterBar/index.tsx:59]: I think these classes should be the defaults of the dropdown - we shouldn't be styling individual dropdowns
