### PR TITLE
fix: missing schedule for the config scrapper form

### LINKED ISSUE #1116: Config scrapers - add schedule

### PR DESCRIPTION
**Pull request by mainawycliffe**
closes #1116

### CODE REVIEW

File: src/components/Forms/Configs/AWSConfigsFormEditor.tsx [hunk 1]
```diff
@@ -25,6 +26,46 @@ export default function AWSConfigsFormEditor({
 
   return (
     <>
+      {/* this a top level schema field, not nested under http */}
+      <FormikAutocompleteDropdown
```
Comment (moshloop) [inline src/components/Forms/Configs/AWSConfigsFormEditor.tsx:30]: Can we extract this into a standalone component ?

Comment (mainawycliffe) [reply src/components/Forms/Configs/AWSConfigsFormEditor.tsx]: Done
