### PR TITLE
fix: show error message when login fails due to invalid credentials

### LINKED ISSUE #2253: Request failed with status code 400 on invalid user/pass

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #2253

### CODE REVIEW

File: src/components/Authentication/Kratos/KratosLogin.tsx [hunk 1]
```diff
@@ -155,6 +157,8 @@ const KratosLogin = () => {
     }
   }, [flow, submitFlow, credentials]);
 
+  console.log("flow", flow);
```
Comment (moshloop) [inline src/components/Authentication/Kratos/KratosLogin.tsx:160]:
```suggestion
```
