### PR TITLE
fix: fix job history duration formatting issue

### LINKED ISSUE #1380: Job history duration formatting
The duration formatting under resolves to seconds for <60s

It should be like the kubernetes duration with special handling for <60s

550ms
12s
2m30s
5h30m

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1380

### CODE REVIEW

File: src/components/JobsHistory/JobsHistoryTableColumn.tsx [hunk 1]
```diff
@@ -51,7 +51,33 @@ export const JobsHistoryTableColumn: ColumnDef<JobHistory, any>[] = [
...
+        parts.push(`${hours}h`);
+      }
+      if (minutes > 0) {
+        parts.push(`${minutes}m`);
+      }
+      const remainingSeconds = (seconds % 60).toFixed(0);
+      if (Number(remainingSeconds) > 0) {
+        parts.push(`${remainingSeconds}s`);
+      }
+      const readableTime = parts.join(" ");
```
Comment (moshloop) [inline src/components/JobsHistory/JobsHistoryTableColumn.tsx:80]:
```suggestion
      const readableTime = parts.join("");
```

File: src/components/JobsHistory/JobsHistoryTableColumn.tsx [hunk 2]
```diff
@@ -51,7 +51,33 @@ export const JobsHistoryTableColumn: ColumnDef<JobHistory, any>[] = [
     size: 100,
     cell: ({ getValue }) => {
       const value = getValue<JobHistory["duration_millis"]>();
-      const readableTime = dayjs.duration(value, "milliseconds").humanize();
+      const duration = dayjs.duration(value, "milliseconds");
```
Comment (moshloop) [inline src/components/JobsHistory/JobsHistoryTableColumn.tsx:54]: This function should probably move to util / or ui so that it is reusable.
