### PR TITLE
fix: incident card styling fixes

### LINKED ISSUE #763: Incident types rendering issues.
The incident items should look the same as sub-components re garding padding/icon sizing placement etc.. - We should have a StatusComponent that handles this rendering. 
Screenshot 2023-01-19 at 11 43 40

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #763

### CODE REVIEW

File: src/components/IncidentStatusTag/index.tsx [hunk 1]
```diff
@@ -15,19 +15,17 @@ const statusClsMap = {
 
 export function IncidentStatusTag({ status, size = "md", className }: IProps) {
   return (
-    <button
-      type="button"
+    <div
```
Comment (moshloop) [inline src/components/IncidentStatusTag/index.tsx:18]: Rather than applying the same style in both places, can we not create a new component with just the styling that is re-used ?

Comment (Prashanth-Nelli) [reply src/components/IncidentStatusTag/index.tsx:18]: sure
