### PR TITLE
fix: page data refresh on hypothesis status is changed to disproven

### LINKED ISSUE #352: Page doesn't refresh after disproving hypothesis in delete window

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #352

### CODE REVIEW

File: src/components/mutations/useUpdateHypothesisMutation.js [hunk 1]
```diff
@@ -1,61 +1,19 @@
...
-          )
-        );
-      }
+    onSuccess: () => {
+      queryClient.refetchQueries(incidentQueryKey);
     },
-    onError: (err, newData, context) => {
-      queryClient.setQueryData(incidentQueryKey, context.previousIncident);
-      queryClient.invalidateQueries(createIncidentQueryKey(incidentId));
+    onError: (err) => {
```
Comment (mainawycliffe) [inline src/components/mutations/useUpdateHypothesisMutation.js:15]: Doesn't Axios already handle these APIs errors or only for GET?

**Review by mainawycliffe — APPROVED** [review]
LGTM

File: src/components/mutations/useUpdateHypothesisMutation.js (hunk 1 above)
Comment (Prashanth-Nelli) [reply src/components/mutations/useUpdateHypothesisMutation.js:15]: Yeah, we already have a global error handler added in one of the response interceptor. This is unnecessary here, I'll remove this.
