### PR TITLE
fix: add pagination support for config insights panel

### LINKED ISSUE #1165: Config insights detail panel paging

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #1165

### CODE REVIEW

File: src/components/Insights/cells/ConfigInsightNameCell.tsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  column,
+  getValue
+}: CellContext<ConfigTypeInsights, unknown>) {
+  const insight = row.original;
+  return (
+    <div
+      data-html={true}
+      data-tip={insight.sanitizedMessageTxt}
+      data-class="max-w-[20rem]"
+      className="py-2 font-medium text-black overflow-hidden cursor-pointer flex-1"
```
Comment (moshloop) [inline src/components/Insights/cells/ConfigInsightNameCell.tsx:16]:
```suggestion
      className="py-2 text-black overflow-hidden cursor-pointer flex-1"
```
