### PR TITLE
1923-topologies-can't-be-edited-if-they-are-being-created-from-ui

### LINKED ISSUE #1904: We should be indicating that some of the config scrapers are from other agents.
image

### LINKED ISSUE #1923: Topologies can't be edited if they are being created from UI
- Also wrongly linked to CRD

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #1923
Fixes #1904

### CODE REVIEW

File: src/components/Settings/CRDSource.tsx [hunk 1]
```diff
@@ -14,11 +14,7 @@ export default function CRDSource({
   namespace,
   source
 }: CRDSourceProps) {
-  if (
-    source !== "KubernetesCRD" &&
-    source !== "Topology" &&
-    !source.startsWith("kubernetes")
-  ) {
+  if (source !== "KubernetesCRD" && !source.startsWith("kubernetes")) {
```
Comment (moshloop) [inline src/components/Settings/CRDSource.tsx:17]:
```suggestion
  if (source === "UI") {
```
